# Generated by Django 4.1.1 on 2023-04-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name="departament, boshqarma yoki bo'lim nomi")),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last name')),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='fathers name')),
                ('birth_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='date of birth')),
                ('living_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Living address')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(blank=True, max_length=150, null=True, verbose_name='mutaxassislik')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=20, verbose_name='start date')),
                ('end_date', models.CharField(max_length=20, verbose_name='end date')),
                ('organization_name', models.CharField(max_length=100, verbose_name='organization name')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_place', to='vacancy.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StartDateOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='start date of work')),
                ('salary', models.CharField(max_length=150, verbose_name='salary')),
                ('information_source', models.CharField(max_length=50, verbose_name='information source')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_date_work', to='vacancy.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='language')),
                ('speaking', models.CharField(blank=True, max_length=20, null=True, verbose_name='speach')),
                ('writing', models.CharField(blank=True, max_length=20, null=True, verbose_name='writing')),
                ('reading', models.CharField(blank=True, max_length=20, null=True, verbose_name='reading')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='vacancy.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_education_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name='name of education institution')),
                ('faculty_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='faculty name')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='specialization')),
                ('completion_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='completion date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='vacancy.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_education_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name='name of education institution')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='specialization')),
                ('completion_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='completion date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_educations', to='vacancy.personalinfo')),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.department'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancy.specialist'),
        ),
    ]
